### ISSUE TITLE
[S|s]irupsen/logrus imports are still broken on Cherami 1.x.x branches

### ISSUE THREAD

**Issue by willhug** [uber/cherami-client-go#29]
The 2.0 branch has been fixed, but, all users who depend on the 1.x.x branches are stuck.  Ideally we should release a 1.22.0 branch that fixes the imports (so that users who have not updated to 2.0 can update and automatically get the fix)

cc @abhinav @akshayjshah

**Comment by akshayjshah** [comment]
This would be really, really great, especially since most users are probably still on the `1.x` release series.

**Comment by datoug** [comment]
ack

**Comment by datoug** [comment]
v1.21.0 is published with the fix: https://github.com/uber/cherami-client-go/releases/tag/v2.1.0
